vmName: fedora
namespace: quali

# Snapshot-only mode: MUST set a valid VolumeSnapshot name present in (this or specified) namespace
volumeSnapshot: ""            # REQUIRED: snapshot name
volumeSnapshotNamespace: ""  # optional; defaults to release namespace if empty

storageSize: 5Gi               # Requested size (>= snapshot content size)
storageClassName: lvm-smartclone

userName: fedora
userPassword: 3t0u-qyyt-g82m
uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
ram: 2Gi
cpu: 1
networks: ""
autoStart: true # may also be provided as a string "true"/"false" and will be coerced to boolean
