apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.network }}
  namespace: {{ .Values.namespace }}
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "{{ .Values.network }}",
      "type": "ovn-k8s-cni-overlay",
      "topology": "layer2",
      "netAttachDefName": "{{ .Values.namespace }}/{{ .Values.network }}"
    }