{{- $suffix := randAlphaNum 6 | lower -}}
{{- $fullName := printf "%s-%s" .Values.vmName $suffix -}}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    cdi.kubevirt.io/storage.usePopulator: "false"
  namespace: {{ .Values.namespace }}
spec:
  sourceRef:
    kind: DataSource
    name: {{ .Values.imageDs }}
    namespace: {{ .Values.imageNs }}
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.storageSize }}
    storageClassName: {{ .Values.storageClassName }}
    volumeMode: Block
