{{- $suffix := randAlphaNum 6 | lower -}}
{{- $fullName := printf "%s-%s" .Values.vmName $suffix -}}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
  namespace: {{ .Values.namespace }}
spec:
  sourceRef:
    kind: DataSource
    name: {{ .Values.imageDs }}
    namespace: {{ .Values.imageNs }}
  storage:
    resources:
      requests:
        storage: {{ .Values.storageSize }}
      storageClassName: lvm-smartclone
