apiVersion: batch/v1
kind: Job
metadata:
  name: "my-script-job"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: my-script-container
          image: busybox  # Use a suitable image (e.g., busybox for simple scripts)
          command:
                  - /bin/sh
                  - -c
                  - |
                    if ! kubectl wait vmi/{{ .Values.vmName }} \
                      --for=condition=AgentConnected \
                      -n {{ .Values.namespace }} \
                      --timeout=600s \
                      >/dev/null 2>&1; then
                      exit 2
                    fi