apiVersion: batch/v1
kind: Job
metadata:
  name: "my-script-job"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: my-script-container
          image: busybox  # Use a suitable image (e.g., busybox for simple scripts)
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for VMI to be Ready…"
              until kubectl wait vmi/{{ .Values.vmName }} \
                         -n {{ .Values.namespace }} \
                         --for=condition=Ready \
                         --timeout=60s; do
                echo "  …still waiting for Ready"
                sleep 10
              done

              echo "Waiting for guest-agent…"
              until kubectl wait vmi/{{ .Values.vmName }} \
                         -n {{ .Values.namespace }} \
                         --for=condition=AgentConnected \
                         --timeout=60s; do
                echo "  …still waiting for AgentConnected"
                sleep 10
              done

              echo "✅ VM fully booted"