apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.vmName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.vmName }}
    kubevirt.io/dynamic-credentials-support: "true"
    vm.kubevirt.io/template: centos-stream9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.34.0
  annotations:
    kubemacpool.io/transaction-timestamp: "2025-07-14T17:12:24.262978538Z"
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1610612736
        }
      ]
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: {{ .Values.vmName }}
      spec:
        sourceRef:
          kind: DataSource
          name: {{ .Values.imageDs }}
          namespace: {{ .Values.imageNs }}
        storage:
          resources:
            requests:
              storage: {{ .Values.storageSize }}
  template:
    metadata:
      labels:
        kubevirt.io/domain: {{ .Values.vmName }}
        kubevirt.io/size: small
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: centos-stream9
        vm.kubevirt.io/workload: server
    spec:
      architecture: amd64
      domain:
        firmware:
          uuid: {{ .Values.uuid }}
        cpu:
          cores: {{ .Values.cpu }}
          sockets: 1
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            {{- if .Values.networks }}
            {{- /* Split by either comma or semicolon */}}
            {{- $networkList := regexSplit "[,;]" .Values.networks -1 }}
            {{- range $index, $networkEntry := $networkList }}
            {{- $networkEntry := $networkEntry | trim }}
            {{- if ne $networkEntry "" }}
            {{- /* Parse network entry safely */}}
            {{- $namespace := $.Release.Namespace }}
            {{- $networkName := $networkEntry }}
            {{- if contains "/" $networkEntry }}
              {{- $nameParts := regexSplit "/" $networkEntry 2 }}
              {{- if gt (len $nameParts) 1 }}
                {{- $namespace = index $nameParts 0 | trim }}
                {{- $networkName = index $nameParts 1 | trim }}
              {{- end }}
            {{- end }}
            {{- /* Generate valid interface name - only allow letters, numbers, dashes and underscores */}}
            {{- $ifaceName := printf "net-%s" $index }}
            - name: net-{{ $index }}
              bridge: {}
              acpiIndex: {{ $index }}
            {{- end }}
            {{- end }}
            {{- end }}
          rng: {}
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: {{ .Values.ram }}
      networks:
        {{- if .Values.networks }}
        {{- /* Split by either comma or semicolon */}}
        {{- $networkList := regexSplit "[,;]" .Values.networks -1 }}
        {{- range $index, $networkEntry := $networkList }}
        {{- $networkEntry := $networkEntry | trim }}
        {{- if ne $networkEntry "" }}
        {{- /* Parse network entry safely */}}
        {{- $namespace := $.Release.Namespace }}
        {{- $networkName := $networkEntry }}
        {{- if contains "/" $networkEntry }}
          {{- $nameParts := regexSplit "/" $networkEntry 2 }}
          {{- if gt (len $nameParts) 1 }}
            {{- $namespace = index $nameParts 0 | trim }}
            {{- $networkName = index $nameParts 1 | trim }}
          {{- end }}
        {{- end }}
        {{- /* Generate valid interface name - only allow letters, numbers, dashes and underscores */}}
        {{- $ifaceName := printf "net-%s" $index }}
        - name: net-{{ $index }}
          multus:
            networkName: {{ printf "%s/%s" $namespace $networkName }}
        {{- end }}
        {{- end }}
        {{- end }}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: {{ .Values.vmName }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: {{ .Values.userName }}
              password: {{ .Values.userPassword }}
              chpasswd: { expire: False }
