apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-vm-{{ .vmName }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: wait-for-vm
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait up to 5 minutes for the VM to become Ready
          kubectl wait vm/{{ .vmName }} \
            --for=condition=Ready \
            --timeout=300s